apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab-ingress
  namespace: gitlab
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - gitlab.k3s.internal
      secretName: gitlab-tls-secret
  rules:
    - host: gitlab.k3s.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitlab-svc
                port:
                  number: 80
